---
output: pdf_document

size: 12pt

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Christopher Junk  
christopher-junk@uiowa.edu  
(309) 313-3071  
Department of Political Science  
University of Iowa  
341 SH  
Iowa City, IA 52242  


\today


Dear Hiring Manager, 

I write to introduce myself as an interested candidate for your analytics development program. I think John Deere provides an exciting and challenging opportunity for me to step outside of political science and expand my skill set in my real passion: data science. Moreover, I think the structure of this program provides me a great setting to learn how John Deere uses data to be successful in many different departments. 

In my coursework at the University of Iowa I have focused on applied statistics to address a wide variety of problems posed by observational data: time series, spatial, network, survival, and multi-level analysis. In each of these settings I have found myself deeply intrigued in the story the methods and data have to tell together about the world. As a result, I am moving forward in this vein using machine learning in my dissertation and looking to leave academia to pursue data science outside of academia. I use ensemble methods to best predict the occurrence of terrorism, protests, and repression throughout the world to assess how effect modern theories of political science predict these events. 

I am proficient in R and Stata, and I am improving my ability to use Python and SQL with freely available online materials and working on my own and collaborative projects. In addition to these abilities, I think joining your data science team gives me a great opportunity to grow and learn about these software and the methods implemented therein.


Thank you for your time and consideration, and I look forward to an opportunity to learn more about the position and the work done at John Deere. 


Sincerely,  
Christopher Junk
