---
output: pdf_document

size: 12pt

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Christopher Junk  
christopher-junk@uiowa.edu  
(309) 313-3071  
<!-- Department of Political Science   -->
<!-- University of Iowa   -->
<!-- 341 SH   -->
<!-- Iowa City, IA 52242   -->


\today


Dear Hiring Manager, 

I am writing to express my interest in the data analytics position USBank currently has available. I am actively pursuing career change into a data analytics and USBank I think offers me a great opportunity to add value to your data analytics team while constantly learning and evolving myself. One of my central goals as a data scientist is to improve and learn every day, in addition to utilizing my toolkit I have already developed. Below, I have enumerated some of my qualifications.

In my coursework at the University of Iowa I have focused on applied statistics and econometrics to address a wide variety of problems posed by observational data types such as: time series, spatial, network, survival, and multi-level  data. In each of these topics I have a deep understanding of the models and experience estimating and interpreting them. I have taken advantage of my time as a graduate student to take classes from experts on these methodologies and to use these tools in my own budding research projects. This allows me both an academic understanding and practical experience in using these models. Furthermore, my background here allows me to quickly pick up new methods. 

As a research assistant I have gained invaluable experience working in a team setting and under time constraints. One example is when Dr. Elizabeth Menninga requested that I write a function to bootstrap a social network to quantify uncertainty of network statistics. In my role I added value by not only writing the function, but improving it by suggesting that bootstrapped network ties should be conditional on certain observed characteristics, depending on the type of network. This project will ultimately be widely applicable to the network analysis community. 

<!-- In one recent web scraping project I gathered, cleaned, and analyzed more than 5,000 comments from an online white supremacist forum. Before starting this project I had no experience with web scraping and within a few hours I was able to teach myself to scrape an entire forum. I turned this data gathering project into a blog post on my [website](https://christopherjunk.netlify.com/blog/2019/05/24/white-extremist-webscrape-frequency-sentiments-and-topics/) in which I do exploratory analysis of long-term forum activity, sentiment analysis, and topic modeling. This project serves as one example of my versatility as a data scientist because of my ability to learn new skills quickly.  -->

In my dissertation I use a variety of machine learning approaches to predict the occurrence of terrorism across time and space. This is particularly difficult because terrorism is such a rare event that predicting it presents substantial challenges. I consider unique features such as spatial and temporal autocorrelation, as well as a myriad of physical, economic, and social features to predict these events. This project has given me invaluable experience in working with uncleaned data and predicting important events. 

I am most proficient in R but I am also quite capable in SQL, Python, and Stata. In addition to these abilities, I think joining your data analytics team gives me a great opportunity to grow and learn as a thinker, data scientist, and coder. 

I thank you for your time and consideration, and I look forward to an opportunity to learn more about the position and the work done at USBank. 


Sincerely,  
Christopher Junk
