---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: C:/Users/Christopher/Documents/data-science/datascience-resume/christopherjunk_datascience_resume.tex
geometry: margin = .8in

title: "CV"
author: Christopher Junk

jobtitle: "Political Science PhD Student"
address: "341 Schaeffer Hall · Iowa City · IA 52242"
fontawesome: yes
email: christopher-junk@uiowa.edu
github: junkpolisci
twitter: Junk_polisci
phone: "309 313 3071"
#web: https://christopherjunk.netlify.com/
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Education

*University of Iowa*, PhD, Political Science \hfill expected 2020  

>Major in statistical methodology and international relations.  

*St. Ambrose University*, BA, International Studies and Spanish \hfill 2016

# Skills & Expertise
__Software Proficiency__: R, Stata, Python  
\n __Methodology__:  Ordinary Least Squares (OLS), Maximum Likelihood Estimation (MLE), Markov-Chain Monte Carlo (MCMC), Time Series, Network Analysis, Spatial Analysis, Machine Learning, Natural Language Processing, Support Vector Machines, Decision Trees, Data Mining 

# Data Experience

__Research Assistant__, "Informal Economies, Societal Stability and Regime Resilience in China and Russia" with William Reisinger, Marina Zaloznaya, Wenfang Tang  \hfill January 2019 - present

  >Managed and cleaned data collected through surveys in China and Russia regards social networks and corruption.
  
  >I used Stata and R to recode and restructure the dataset for use in analyses as well as estimating and interpreting analyses and reporting findings to the primary researchers.  

__Managing Editor & Replication Analyst__, Foreign Policy Analysis \hfill May 2018 - present  

>As managing editor I handle plagiarism reports, proofreading, and general workflow of manuscripts from submission to publication. 

>As replication analyst I attempt to replicate the empirical analyses in manuscripts and correspond with authors to assure validity of inferences and correct coding practices.  

__Collaboratory Manager__, Department of Political Science, University of Iowa \hfill August 2018 - January 2019  

>I managed the updating and maintenance of the computer lab for graduate students and undergrads enrolled in statistical courses. 

>I served as an informal TA for undergraduate and graduate statistics courses. 

>Assist undergraduate and graduate students in statistical modeling and analysis. 

# Working Papers


*Democratic Repression: Responding in Kind?*  

> In this paper I use webscraped events data (SPEED Project) to analyze the dynamic relationship between public dissent and state repression. Using a series of random effects logit models I find that democracies typically respond to dissent with an equivalent use of force. 

*Terrorism and Spanish Elections: Does Terrorism Impact Support for the Central Government?*

> In this paper I use Spanish polling data to assess the impact of terrorism in Spain on support for the two major political parties. Using time series models (ADL and GECM) I find that only particularly catastrophic events influence public opinion, while average terrorism has no effect. 

# Conferences Presentations

Midwest Political Science Association (2019)  
Iowa Association of Political Scientists (2014, 2016)







<!-- #Relevant Coursework -->

<!-- *POLI:5001	Introductory Methodology*: Learned probability theory and other basic building blocs of advanced statistical analyses for use in social science research.   -->

<!-- *POLI:5003	Intermediate Methodology*: Covered the assumptions and implementation of ordinary least squares (OLS) regression as well as alternative methods, such as dealing with binary dependent variables.   -->

<!-- *POLI:7003	Advanced Methodology*: A wide variety of more advanced methods using data from complex social science data generating processes. Some methods covered here include causal inference, interpolation/imputation, survey analyses, multilevel modeling, and time series analysis.  -->

<!-- *POLI:7002	Time Series Analysis*: This course covered methodology used in the instances of time series, both single time series and cross-sectional analyses. Methodology covered include: AR(F)IMA, (G)ARCH, autoregressive distributed lag models (ADL), error-correction models (ECM), causal inference, time varying parameters, and system of equations/vector autoregression.  -->

<!-- *POLI:7002	Networks*: In this course I learned how to model interconnectednesss in a network setting and use the inclusion of observation-dependency as an aspect of a model's analytic ability. Methodology covered includes: conditional uniform graph (CUG) tests, community detection, diffusion, network (logistic) regression, and the ERGM/SAOM class of models.  -->

<!-- *POLI:7002	Modeling Time and Space*: Covered methodology relating to multi-level structure of data, duration analyses, and spatial analysis methodology.  -->

<!-- *POLI:7450	Computational Methods for Comparative Politics*: Use a wide variety of methodology such as web scraping, text analysis, multi-level models, survey analysis, latent variables, and broad reproducible practice for data management and analysis.   -->



