---
output: 
  pdf_document:
    latex_engine: pdflatex
    
geometry: margin = .5in

header-includes:
    - \usepackage{setspace}\singlespacing

---


Pursuing a career in data science to help businesses make data-informed decisions. Relocating to Denver, CO July 1st.  


### Education

*University of Iowa*, PhD, Political Science \hfill expected Dec 2019  

*  Major in econometrics and international relations. 

*University of Iowa*, MA, Political Science \hfill May 2019  
*St. Ambrose University*, BA, International Studies and Spanish \hfill May 2016

### Projects  

*__Dissertation__: Political Prediction acros Space and Time: Ensemble Machine Learning to Predict Terrorism and Protests*  

> Build ensemble machine learning models to predict political events as locally as possible and at the finest temporal aggregation possible.  
> Gather, clean, and collect geocoded event, climate, terrain, socio-economic, and historical data. Transform this data into usable format for analysis from a variety of storage types (e.g. shape files, raster files, webscraping). 

*White Extremist Web Scrape: Frequency, Sentiments, and Topics* 

> Scrape more than 5,000 comments automatically from an online White Supremacist forum discussing ideology/philosophy. Visualize the forum's activity in a variety of ways including: activity over time, most used words, most active users, sentiment analysis, and more. 

> Conduct sentiment analysis, and Latent Dirichlet Allocation topic modeling. Accessible via my website [blog](https://christopherjunk.netlify.com/blog/2019/05/24/white-extremist-webscrape-frequency-sentiments-and-topics/). 

*Democratic Repression: Responding in Kind?*  

* Restructure events data to country-month unit of analysis. Clean and restructure a variety of standard controls in political science research (regime type, economic indicators, conflict history, etc.) and join for full analysis. 

* Estimate multilevel logistic models to model the relationship between domestic political dissent and state repression in democracies. I conclude that democracies repress as a response to political dissent, despite their political promise not to. Rough draft available via my [GitHub page](https://github.com/junkpolisci/democracy_repression/blob/master/democratic_repression.pdf). 

*Terrorism and Spanish Elections: Does Terrorism Impact Support for the Central Government?*

> Estimate time series analysis to assess the impact of terrorism in Spain on support for the central government using machine coded events data and Spanish polling data. 

> Compare and contrast the autoregressive distributed lag (ADL) model and general error correction model (GECM) as part of a debate in the econometric political science literature. 

<!-- In this paper I use Spanish polling data to assess the impact of terrorism in Spain on support for the two major political parties. Using time series models (ADL and GECM) I find that only particularly catastrophic events influence public opinion, while average terrorism has no effect. -->




### Quantitative Experience
<!-- # Skills & Expertise -->
__Software Proficiency__: R, Stata, Python, SQL  
<!-- __Methodology__:  Ordinary Least Squares (OLS), Logistic Regression, Time Series, Network Analysis, Spatial Analysis, Machine Learning, Natural Language Processing, Support Vector Machines, Decision Trees, Data Mining   -->
Research Assistant - Dr. Elizabeth Menninga \hfill Summer 2019  

> Develop a method of simulating social networks conditional on the observed network via bootstrapping to quantify uncertainty of network statistics in R.

Research Assistant - Dr. Bryce Dietrich \hfill Summer 2019  

> Use millions of tweets to quantify 'otherization' of immigrants in the context of modern immigration events in R. 

Research Assistant - Dr. William Reisinger, Dr. Marina Zaloznaya, Dr. Wenfang Tang  \hfill Spring 2019  

> Estimate regression and classification analysis on novel corruption survey data in China and Russia. I also created egonets out of embedded network vignettes in the survey. 


<!-- *Managing Editor/Replication Analysts Foreign Policy Analysis* -->

<!-- > Manage originality reports and workflow of over 200+ manuscripts per year. Assist the editorial team in reviewing and publishing manuscripts.   -->

<!-- > Reproduce empirical models of all published articles (20+ per year).  -->

<!-- *Teaching Assistantships*  -->

<!-- Fall 2016; Spring 2017; Summer 2017; Fall 2017; Spring 2018 -->
<!-- # Conferences Presentations -->

<!-- Midwest Political Science Association (2019)   -->
<!-- Iowa Association of Political Scientists (2014, 2016) -->


<!-- #Relevant Coursework -->

<!-- *POLI:5001	Introductory Methodology*: Learned probability theory and other basic building blocs of advanced statistical analyses for use in social science research.   -->

<!-- *POLI:5003	Intermediate Methodology*: Covered the assumptions and implementation of ordinary least squares (OLS) regression as well as alternative methods, such as dealing with binary dependent variables.   -->

<!-- *POLI:7003	Advanced Methodology*: A wide variety of more advanced methods using data from complex social science data generating processes. Some methods covered here include causal inference, interpolation/imputation, survey analyses, multilevel modeling, and time series analysis.  -->

<!-- *POLI:7002	Time Series Analysis*: This course covered methodology used in the instances of time series, both single time series and cross-sectional analyses. Methodology covered include: AR(F)IMA, (G)ARCH, autoregressive distributed lag models (ADL), error-correction models (ECM), causal inference, time varying parameters, and system of equations/vector autoregression.  -->

<!-- *POLI:7002	Networks*: In this course I learned how to model interconnectednesss in a network setting and use the inclusion of observation-dependency as an aspect of a model's analytic ability. Methodology covered includes: conditional uniform graph (CUG) tests, community detection, diffusion, network (logistic) regression, and the ERGM/SAOM class of models.  -->

<!-- *POLI:7002	Modeling Time and Space*: Covered methodology relating to multi-level structure of data, duration analyses, and spatial analysis methodology.  -->

<!-- *POLI:7450	Computational Methods for Comparative Politics*: Use a wide variety of methodology such as web scraping, text analysis, multi-level models, survey analysis, latent variables, and broad reproducible practice for data management and analysis.   -->



